from datetime import datetime
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, ConfigDict, Field, model_validator, field_validator


class SectionSchema(BaseModel):
    """Pydantic schema for track sections."""

    section_id: str
    name: str
    line_type: str
    start_station: str
    end_station: str
    start_km: float
    end_km: float
    max_speed_kmh: int
    traffic_density_index: float

    model_config = ConfigDict(from_attributes=True)


class AssetConditionFeatures(BaseModel):
    """Encompassing container for 6 asset condition & degradation features."""

    asset_age_years: float = Field(..., ge=0.0)
    last_maintenance_days_ago: int = Field(..., ge=0)
    past_breakdown_count: int = Field(..., ge=0)
    gross_million_tonnes: float = Field(..., ge=0.0)
    condition_score: float = Field(..., ge=1.0, le=10.0)
    urgency_category: str

    model_config = ConfigDict(from_attributes=True)


class MaintenanceRequestResponse(BaseModel):
    """Unified maintenance request response schema matching ARCHITECTURE.md Section 4.2."""

    request_id: str
    source_system: str
    department: str
    section_id: str
    corridor_slot: str
    chainage_start: float
    chainage_end: float
    requested_window_start: datetime
    requested_window_end: datetime
    required_duration_minutes: int
    work_type: str
    asset_id: str
    asset_type: str
    asset_age_years: float
    last_maintenance_days_ago: int
    past_breakdown_count: int
    gross_million_tonnes: float
    condition_score: float
    urgency_category: str
    asset_age_or_condition_features: Optional[Dict[str, Any]] = None
    asset_condition_features: Optional[Dict[str, Any]] = None
    risk_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=100.0,
        description="Tabular ML failure risk and scheduling priority score (0.0 to 100.0) generated by LightGBM model",
    )
    requires_power_block: bool
    requires_traffic_block: bool
    status: str = "PENDING"

    model_config = ConfigDict(from_attributes=True)

    @model_validator(mode="after")
    def populate_feature_containers(self) -> "MaintenanceRequestResponse":
        features = self.asset_age_or_condition_features or self.asset_condition_features
        if not features:
            features = {
                "asset_age_years": self.asset_age_years,
                "last_maintenance_days_ago": self.last_maintenance_days_ago,
                "past_breakdown_count": self.past_breakdown_count,
                "gross_million_tonnes": self.gross_million_tonnes,
                "condition_score": self.condition_score,
                "urgency_category": self.urgency_category,
            }
        self.asset_age_or_condition_features = features
        self.asset_condition_features = features

        # Auto-compute predictive risk score if missing
        if self.risk_score is None:
            try:
                from app.risk_model import predict_risk_score
                self.risk_score = predict_risk_score(features)
            except Exception:
                self.risk_score = 0.0

        return self


class RiskPredictionInput(BaseModel):
    """Input payload for on-demand asset failure risk inference."""

    asset_age_years: float = Field(..., ge=0.0, description="Asset age in years")
    last_maintenance_days_ago: int = Field(..., ge=0, description="Days elapsed since previous maintenance")
    past_breakdown_count: int = Field(..., ge=0, description="Defect/breakdown count in past 12 months")
    gross_million_tonnes: float = Field(..., ge=0.0, description="Cumulative dynamic traffic tonnage load")
    condition_score: float = Field(..., ge=1.0, le=10.0, description="Physical condition score (1.0 degraded to 10.0 pristine)")
    urgency_category: str = Field(..., description="Operational urgency tier (LOW, MEDIUM, HIGH, CRITICAL)")
    request_id: Optional[str] = Field(None, description="Optional associated maintenance request ID")

    @field_validator("urgency_category")
    @classmethod
    def validate_urgency(cls, v: str) -> str:
        cleaned = str(v).strip().upper()
        if cleaned not in {"LOW", "MEDIUM", "HIGH", "CRITICAL"}:
            raise ValueError(f"Invalid urgency_category '{v}'. Expected one of: LOW, MEDIUM, HIGH, CRITICAL")
        return cleaned


class RiskPredictionResponse(BaseModel):
    """Response payload containing LightGBM risk score and operational priority tier."""

    request_id: Optional[str] = None
    risk_score: float = Field(..., ge=0.0, le=100.0, description="Predicted risk score (0.0 to 100.0)")
    risk_tier: str = Field(..., description="Operational urgency tier: CRITICAL (>=75), HIGH (>=50), MEDIUM (>=25), LOW (<25)")
    features: Dict[str, Any]


class IngestionErrorDetail(BaseModel):
    record_id: Optional[str] = None
    errors: List[str]


class IngestionResult(BaseModel):
    """Summary of data ingestion operation."""

    sections_ingested: int = 0
    requests_ingested: int = 0
    requests_rejected: int = 0
    total_evaluated: int = 0
    validation_errors: List[IngestionErrorDetail] = []


# ==============================================================================
# Phase 4 Optimization Schemas (CP-SAT Block Scheduling & Bundling)
# ==============================================================================

class ConstituentRequestSummarySchema(BaseModel):
    """Summary of an individual request constituent bundled into a block."""

    request_id: str
    department: str
    work_type: str
    asset_id: str
    asset_type: str
    chainage_start: float
    chainage_end: float
    requested_window_start: str
    requested_window_end: str
    required_duration_minutes: int
    scheduled_start: str
    scheduled_end: str
    risk_score: float
    requires_power_block: bool
    requires_traffic_block: bool


from app.explainer import (
    MergedRequestDetail,
    PriorityReasoning,
    WindowBounds,
    ConstraintReasoning,
    AlternativesReasoning,
    BlockExplanation,
)


class BundledBlockSchema(BaseModel):
    """Optimized consolidated maintenance possession block with Phase 5 structured explanation."""

    block_id: str
    section_id: str
    corridor_slot: str
    start_km: float
    end_km: float
    scheduled_start: str
    scheduled_end: str
    total_duration_minutes: int
    bundled_request_ids: List[str]
    departments_involved: List[str]
    power_block_granted: bool
    traffic_block_granted: bool
    savings_minutes: int
    explanation_text: str
    explanation_detail: Optional[BlockExplanation] = None
    explanation: Optional[BlockExplanation] = None
    approval_status: str = "PROPOSED"
    constituent_requests: List[ConstituentRequestSummarySchema] = []
    is_modified: Optional[bool] = False
    delta_type: Optional[str] = None

    @model_validator(mode="after")
    def sync_explanation_fields(self) -> "BundledBlockSchema":
        if self.explanation is None and self.explanation_detail is not None:
            self.explanation = self.explanation_detail
        elif self.explanation_detail is None and self.explanation is not None:
            self.explanation_detail = self.explanation
        return self


class BaselineScheduleMetrics(BaseModel):
    """Quantitative before/after comparison between naive baseline and CP-SAT optimized schedule."""

    baseline_block_count: int = Field(..., description="Total unbundled baseline blocks (equal to total requests)")
    optimized_block_count: int = Field(..., description="Total CP-SAT optimized possession blocks")
    block_count_reduction: int = Field(..., description="Absolute reduction in required track possessions")
    block_count_reduction_pct: float = Field(..., description="Percentage reduction in track blocks")
    baseline_possession_minutes: int = Field(..., description="Total cumulative baseline line possession minutes")
    baseline_possession_hours: float = Field(..., description="Total baseline possession hours")
    optimized_possession_minutes: int = Field(..., description="Total optimized bundled line possession minutes")
    optimized_possession_hours: float = Field(..., description="Total optimized possession hours")
    possession_savings_minutes: int = Field(..., description="Total line possession minutes saved")
    possession_savings_hours: float = Field(..., description="Total line possession hours saved")
    possession_reduction_pct: float = Field(..., description="Percentage of line possession saved")
    baseline_traffic_halts: int = Field(..., description="Number of separate train traffic stoppage events in baseline")
    optimized_traffic_halts: int = Field(..., description="Number of train traffic stoppage events in optimized plan")
    avoided_traffic_halts: int = Field(..., description="Avoided train traffic stoppages through bundling")
    coordinated_bundles_created: int = Field(..., description="Total cross-departmental bundles formed")
    triple_department_bundles: int = Field(..., description="Bundles combining Engineering + S&T + TRD")
    dual_department_bundles: int = Field(..., description="Bundles combining 2 departments")


class OptimizationPlanResponse(BaseModel):
    """Complete response payload for CP-SAT block scheduling optimization plan."""

    status: str
    total_requests_in: int
    total_blocks_out: int
    bundled_blocks_count: int
    single_blocks_count: int
    total_original_duration_minutes: int
    total_bundled_duration_minutes: int
    total_savings_minutes: int
    savings_percentage: float
    solve_time_seconds: float
    blocks: List[BundledBlockSchema]
    reoptimization_mode: Optional[str] = "FULL"
    delta_request_ids: Optional[List[str]] = []
    affected_blocks_count: Optional[int] = 0
    baseline_comparison: Optional[BaselineScheduleMetrics] = None


class OptimizationPlanInput(BaseModel):
    """Input payload for POST /optimize endpoint."""

    requests: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Optional explicit list of maintenance requests to optimize. If omitted or empty, current database requests are utilized.",
    )
    spatial_proximity_km: Optional[float] = Field(
        default=2.0,
        ge=0.1,
        le=50.0,
        description="Proximity threshold in km for cross-departmental spatial bundling.",
    )
    max_block_km_span: Optional[float] = Field(
        default=15.0,
        ge=1.0,
        le=100.0,
        description="Maximum physical km span allowed for a single consolidated block.",
    )
    delta_mode: Optional[bool] = Field(
        default=False,
        description="When True, enables fast localized delta re-optimization by re-solving only affected subproblems.",
    )
    modified_request_ids: Optional[List[str]] = Field(
        default=None,
        description="List of request IDs that were modified in what-if simulation, targeting localized re-solve.",
    )
    recompute_risk: Optional[bool] = Field(
        default=False,
        description="Whether to recompute risk scores with LightGBM for requests whose urgency changed.",
    )


class BlockExplainResponse(BaseModel):
    """Detailed response for GET /api/v1/blocks/{block_id}/explain endpoint."""

    block_id: str
    explanation_text: str
    explanation_detail: BlockExplanation
    explanation: Optional[BlockExplanation] = None

    @model_validator(mode="after")
    def sync_explanation_fields(self) -> "BlockExplainResponse":
        if self.explanation is None and self.explanation_detail is not None:
            self.explanation = self.explanation_detail
        return self


class BlockActionInput(BaseModel):
    """Payload for Controller approval/rejection of a scheduled block."""

    action: str = Field(..., description="Controller action: APPROVE, REJECT, MODIFIED")
    controller_notes: Optional[str] = Field(None, description="Optional justification or operating notes")


class BlockActionResponse(BaseModel):
    """Response payload for Controller block action."""

    block_id: str
    action: str
    status: str
    message: str


